# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4690442df45d78d3fd024e9a0ee384158d923dfcf576ec11facea0df48bc1b58fedec857193e20af960dccae14cc99615664c4207c7eac4860e67bec24636d16

test:
  secret_key_base: 3c858c38a78e16d1961d1a3059cab39db35fe5602d41fe30c00104a0c4bd6c3a69568c0e588bb078ed597d56edb6efca680e8053eafa8b9f3c82f8e4aad91168

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
